import os
import sys

curr_folder = os.path.dirname(os.path.realpath(__file__))
sys.path.extend([os.path.dirname(curr_folder)])
import content_grabber as cg
import database_tools as dt

# save_folder = r"G:\temp"
# save_folder = r"D:\temp"
save_folder = r"F:\webpage_translation"

# url = "https://www.space.com/spacex-starship-launch-debris-terrifying"
# url = "https://www.space.com/nasa-voyager-mission-engineers-documentary"
# url = "https://www.space.com/voyager-1-45-year-launch-anniversary"
# url = "https://spacenews.com/esa-troublseshooting-juice-radar-antenna/"
# url = "https://www.space.com/voyager-2"
# url = "https://www.space.com/why-take-juice-spacecraft-eight-years-reach-jupiter"
# url = "https://spacenews.com/chinas-mystery-reusable-spaceplane-lands-after-276-days-in-orbit/"
# url = "https://www.space.com/moon-time-lunar-clock-debate-wristwatch"
# url = "https://www.space.com/nasa-selects-blue-origin-second-artemis-moon-lander"
# url = "https://www.space.com/18377-new-horizons.html"
# url = "https://www.space.com/nasa-juno-jupiter-io-volcanic-moon-images"
# url = "https://spacenews.com/exploration-upper-stage-unveiled-revolutionary-leap-in-crew-safety-cargo-capacity-and-deep-space-power"
# url = "https://www.space.com/gravitational-lensing-explained"
# url = "https://www.space.com/space-solar-power-satellite-beams-energy-1st-time"
# url = "https://www.space.com/euclid-spacecraft-named-after-mathematician"
# url = "https://www.space.com/starlink-satellite-conjunction-increase-threatens-space-sustainability"
# url = "https://www.space.com/how-long-could-you-survive-in-space-without-spacesuit"
# url = "https://www.space.com/largest-radio-telescope-smart-maintenance-robots"
# url = "https://www.space.com/soviet-satellite-breaks-apart-after-debris-strike"
# url = "https://www.space.com/what-are-kilonovas"
# url = "https://spacenews.com/nasa-starts-reassessment-of-mars-sample-return-architecture/"
# url = "https://www.space.com/china-worlds-largest-underwater-telescope-hunt-for-elusive-ghost-particles"
# url = "https://www.space.com/expert-voice-what-is-an-attosecond"
# url = "https://www.space.com/spacex-starship-second-test-flight-launch-explodes"
# url = "https://www.space.com/space-force-x-37b-spacex-falcon-heavy-1st-launch-dec-2023"
# url = "https://spacenews.com/nasa-slows-down-work-on-mars-sample-return-due-to-budget-uncertainty/"
# url = "https://spacenews.com/satellite-imagery-reveals-explosion-at-chinas-jiuquan-spaceport/"
# url = "https://spacenews.com/china-makes-progress-on-raptor-like-engines-for-super-heavy-rocket/"
# url = "https://www.space.com/what-are-radio-galaxies"
# url = "https://www.space.com/nasa-x-59-quesst-paint-job"
# url = "https://www.space.com/mars-rotor-system-test-nears-supersonic-speeds-ingenuity-flies-coincides"
# url = "https://www.space.com/china-space-plane-depoyed-mystery-objects"
# url = "https://www.space.com/mars-rotor-system-test-nears-supersonic-speeds-ingenuity-flies-coincides"
# url = "https://www.space.com/15787-johannes-kepler.html"
# url = "https://www.space.com/nasa-removes-stuck-fasteners-osiris-rex-asteroid-samples"
# url = "https://www.space.com/astrobotic-peregrine-moon-lander-headed-to-earth"
# url = "https://spacenews.com/moores-law-space/"
# url = "https://spacenews.com/chinas-change-6-probe-arrives-at-spaceport-for-first-ever-lunar-far-side-sample-mission/"
# url = "https://www.space.com/solar-maximum-in-sight-but-scientists-will-have-to-wait-seven-months-after-it-occurs-to-officially-declare-it"
# url = "https://www.space.com/nasa-jpl-layoffs-february-2024-mars-sample-return"
# url = "https://www.space.com/nasa-voyager-spacecraft-mission-deep-space-update"
# url = "https://www.space.com/mars-ingenuity-helicopter-blade-mars-perseverance-photo"
# url = "https://www.space.com/spacex-starship-flight-3-launch-what-time"
# url = "https://www.space.com/spacex-starship-third-test-flight-launch"
# url = "https://spacenews.com/surprise-chinese-lunar-mission-hit-by-launch-anomaly/"
# url = "https://www.space.com/voyager-1-communications-update-fds-memory-issue"
# url = "https://spacenews.com/china-appears-to-be-trying-to-save-stricken-spacecraft-from-lunar-limbo/"
# url = "https://www.space.com/mars-giant-volcano-hiding-plain-sight"
# url = "https://www.space.com/object-crash-florida-home-iss-space-junk-nasa-confirms"
# url = "https://www.space.com/ingenuity-mars-helicopter-flight-map-video-2024"
# url = "https://www.space.com/china-reusable-rocket-aces-key-engine-tests"
# url = "https://www.space.com/china-tiangong-space-station-space-debris-measures"
# url = "https://www.space.com/what-is-solar-maximum-and-when-will-it-happen"
# url = "https://www.space.com/boeing-starliner-crew-flight-test-launch-pad-rollout"
# url = "https://www.space.com/boeing-starliner-nasa-astronauts-delay-emotional-rollercoaster-launch"
# url = "https://spacenews.com/chinas-change-6-is-carrying-a-surprise-rover-to-the-moon/"
# url = "https://www.space.com/satellite-images-rafah-israel-gaza"
# url = "https://www.space.com/spacex-crew-dragon-trunk-space-debris-canada"
# url = "https://www.space.com/voyager-1-mission-glitch-engineers-weighing-in-lucky-peanuts"
# url = "https://www.space.com/japan-slim-mission-unresponsive-jaxa-signal"
# url = "https://www.space.com/japanese-billionaire-cancels-spacex-starship-moon-dearmoon-flight"
# url = "https://www.space.com/boeing-starliner-crew-flight-test-launch"
# url = "https://www.space.com/spacex-starship-flight-4-test-launch-success"
# url = "https://spacenews.com/spacex-and-the-categorical-imperative-to-achieve-low-launch-cost/"
# url = "https://www.space.com/mars-water-frost-equator-exomars-tharsis-olympus-mons"
# url = "https://www.space.com/boeing-starliner-helium-leaks-assessment"
# url = "https://spacenews.com/voyager-1-returning-science-data-again/"
# url = "https://www.space.com/shenzhou-18-second-spacewalk-tiangong-space-debris-shield"
# url = "https://spacenews.com/europe-set-for-crucial-first-launch-of-ariane-6/"
# url = "https://www.space.com/what-are-blazars-complete-guide"
# url = "https://www.space.com/europe-clipper-transistors-vulnerable-radiation"
# url = "https://spacenews.com/china-reschedules-planetary-defense-mission-for-2027-launch/"
# url = "https://www.space.com/spacex-rocket-failure-nasa-astronaut-launch-schedule-iss"
# url = "https://www.space.com/iss-deorbit-destroy-spacex-vehicle-18-months"
# url = "https://spacenews.com/china-prepares-to-launch-new-long-march-12-rocket/"
# url = "https://spacenews.com/enhanced-dragon-spacecraft-to-deorbit-the-iss-at-the-end-of-its-life/"
# url = "https://www.space.com/nasa-cancels-viper-moon-rover-budget"
# url = "https://www.space.com/spacex-starlink-50000-collision-avoidance-maneuvers-space-safety"
# url = "https://www.space.com/china-change-6-mini-moon-rover-training-video"
# url = "https://www.space.com/mercury-diamond-layer-10-miles-thick-nasa-messenger"
# url = "https://www.space.com/spacex-crew-9-iss-astronaut-space-junk-dragon"
# url = "https://spacenews.com/spacex-to-move-dragon-splashdowns-back-to-west-coast/"
# url = "https://www.space.com/chandra-25-years-celebration-nasa"
# url = "https://spacenews.com/chinese-scientists-outline-major-cislunar-space-infrastructure-project/"
# url = "https://www.space.com/boeing-starliner-nasa-astronauts-not-stranded-space"
# url = "https://spacenews.com/boeing-takes-additional-125-million-loss-on-starliner/"
# url = "https://www.space.com/settling-other-planets-will-mean-human-genome-editing"
# url = "https://spacenews.com/china-launches-first-satellites-for-thousand-sails-megaconstellation/"
# url = "https://www.space.com/spacex-crew-9-launch-delay-september-24"
# url = "https://www.space.com/boeing-starliner-iss-astronaut-schedule-flux"
# url = "https://spacenews.com/chinese-rocket-stage-breaks-up-into-cloud-of-more-than-700-pieces-of-space-debris/"
# url = "https://spacenews.com/nasa-watchdog-finds-quality-control-problems-with-boeing-sls-work/"
# url = "https://www.space.com/china-cas-space-reusable-rocket-progress"
# url = "https://www.space.com/researchers-want-to-build-streetlights-on-the-moon"
# url = "https://spacenews.com/china-could-develop-dual-relay-satellite-system-for-earth-moon-communications-to-reduce-geopolitical-risks/"
# url = "https://spacenews.com/rethinking-safety-in-the-age-of-machine-complexity/"
# url = "https://spacenews.com/chinese-spacecraft-appear-to-reach-lunar-orbit-despite-launch-setback/"
# url = "https://www.space.com/rocket-factory-augsburg-explosion-saxavord-spaceport"
# url = "https://www.space.com/perseverance-mars-rover-sample-return"
# url = "https://spacenews.com/china-to-launch-earth-2-0-exoplanet-observatory-in-2028/"
# url = "https://www.space.com/nasa-boeing-starliner-astronauts-will-return-on-spacex-dragon-2025"
# url = "https://spacenews.com/starliner-to-return-from-iss-without-astronauts-on-board/"
# url = "https://www.space.com/spacex-polaris-dawn-private-spacewalk-explainer"
# url = "https://www.space.com/juice-jupiter-probe-earth-flyby-complete"
# url = "https://spacenews.com/falcon-9-booster-lost-in-rare-unsuccessful-landing/"
# url = "https://www.space.com/jaxa-slim-moon-lander-dead"
# url = "https://www.space.com/blue-origin-new-glenn-debut-launch-escapade-mars-october-2024"
# url = "https://www.space.com/nasa-solar-sail-deployment"
# url = "https://www.space.com/unbreakable-quantum-communication-bright-photons"
# url = "https://spacenews.com/china-launches-new-set-of-classified-yaogan-43-satellites/"
# url = "https://www.space.com/boeing-starliner-spacecraft-tension-return-earth-without-astronauts"
# url = "https://spacenews.com/china-to-launch-mars-sample-return-mission-in-2028-will-follow-planetary-protection-guidelines/"
# url = "https://www.space.com/boeing-starliner-astronauts-nasa-spacex-crew-dragon"
# url = "https://spacenews.com/chinas-secretive-reusable-spaceplane-lands-after-267-days-in-orbit/"
# url = "https://www.space.com/boeing-starliner-lands-earth-crew-flight-test-mission"
# url = "https://www.space.com/china-moon-bricks-test-tiangong-space-station"
# url = "https://www.space.com/spacex-polaris-dawn-astronaut-mission-launch-success"
# url = "https://spacenews.com/china-is-taking-a-keen-interest-in-lava-tubes-as-possible-lunar-habitats/"
# url = "https://www.space.com/voyager-1-interstellar-space-thruster-fix"
# url = "https://www.space.com/spacex-starship-flight-five-late-november"
# url = "https://www.space.com/starship-super-heavy-wind-tunnel-tests"
# url = "https://www.space.com/spacex-polaris-dawn-private-astronaut-mission-splashdown"
# url = "https://www.space.com/china-long-march-8a-1st-launch-preparations"
# url = "https://www.space.com/faa-fining-spacex-launches-2023"
# url = "https://spacenews.com/india-approves-moon-sample-return-venus-orbiter-space-station-module-and-reusable-launcher/"
# url = "https://www.space.com/china-yutu-2-rover-moon-far-side-2024-video"
# url = "https://www.space.com/second-kuiper-belt-solar-system-larger-than-thought"
# url = "https://www.space.com/china-change-6-lunar-samples-results"
# url = "https://spacenews.com/deep-blue-aerospace-hop-test-suffers-anomaly-moments-before-landing/"
# url = "https://spacenews.com/china-set-to-unveil-long-term-vision-for-space-science/"
# url = "https://www.space.com/spacex-starship-super-heavy-booster-retrieved-sea-photo"
# url = "https://www.space.com/china-space-plane-image-delta-wing-design"
# url = "https://www.space.com/blue-origin-new-glenn-upper-stage-hotfire-test-video"
# url = "https://www.space.com/spacex-pause-launches-crew-9-falcon-9-issue"
# url = "https://spacenews.com/china-to-launch-near-earth-asteroid-sample-return-mission-in-2025/"
# url = "https://www.space.com/china-fast-radio-telescope-24-new-dishes"
# url = "https://www.space.com/voyager-2-science-instrument-shut-off"
# url = "https://www.space.com/most-powerful-solar-flare-this-solar-cycle-x-9-earth-firing-line"
# url = "https://www.space.com/curiosity-mars-rover-wheel-damage-sept-2024"
# url = "https://www.space.com/nasa-tess-record-breaking-three-star-system-tightly-packed"
# url = "https://spacenews.com/brightness-of-first-chinese-broadband-constellation-satellites-alarms-astronomers/"
url = "https://www.space.com/future-space-technologies-world-space-week"


text_dict = cg.get_text_from_html(url=url)
h5_path = dt.save_html_content(text_dict=text_dict, folder=save_folder)

dt.translate_h5_file(
    h5_path=h5_path,
    model="gpt-4-1106-preview",
    #  model="gpt-3.5-turbo",
    max_len=50000,
    temperature=0,
)

dt.save_text_files(h5_path)
